### ISSUE TITLE
Languages folder must be in root directory

### ISSUE THREAD

**Issue by PXJesse** [IcarusWS/langic#1]
The documentation tells us to put the "languages" folder in the _same directory_ as the langic.js script. However, the browser returns an error because it's looking for the languages folder in the _directory where the HTML file is located_ instead of in the same folder as the langic.js script.

Example:
When the langic.js script is initialized from _https://example.com/icarus/index.php_ like this:
`<script src="scripts/langic/langic.js"></script>`
and the languages folder is located at
`https://example.com/icarus/scripts/langic/languages`

The browser returns the following error:
`langic.js:49 GET https://example.com/icarus/languages/english.lang.json 404 (Not Found)`

The reason this issue happens is because the script is initialized in the HTML file, and all paths are taken relatively from there. This means that `var path = 'languages/' + language + '.lang.json';` (langic.js:17) will be relative to the directory of the HTML file.

**Comment by IcarusWS** [comment]
This is indeed an issue, because it should be an absolute path.
I should fix this in the next version.

**Comment by IcarusWS** [comment]
Fixed the issue in commit [b1d423d](https://github.com/IcarusWS/langic/commit/b1d423d41a6d12d37bfc80d752d751978abd1878).
Now you can set your own path
